---

- name: AWS Get STS Credentials
  local_action:
    module: sts_assume_role
    profile: "{{sts_profile}}"
    region: "{{region}}"
    mfa_serial_number: "{{sts_mfa | default(omit)}}"
    mfa_token: "{{sts_mfatoken | default(omit)}}"
    role_arn: "{{sts_role_arn}}"
    role_session_name: "{{sts_role_session_name}}"
  register: assumed_role
  when: sts

- name: Retreive STS Credentials
  set_fact:
    sts_aws_access_key: "{{ hostvars['localhost']['assumed_role'].sts_creds.access_key }}"
    sts_aws_secret_key: "{{ hostvars['localhost']['assumed_role'].sts_creds.secret_key }}"
    sts_security_token: "{{ hostvars['localhost']['assumed_role'].sts_creds.session_token }}"
  when: sts